package v1

import "k8s.io/apimachinery/pkg/runtime"

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *NodeStatus) DeepCopyInto(out *NodeStatus) {
	*out = *in
	if in.LastFailedTime != nil {
		in, out := &in.LastFailedTime, &out.LastFailedTime
		*out = (*in).DeepCopy()
	}
	if in.LastFailedRevisionErrors != nil {
		in, out := &in.LastFailedRevisionErrors, &out.LastFailedRevisionErrors
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new NodeStatus.
func (in *NodeStatus) DeepCopy() *NodeStatus {
	if in == nil {
		return nil
	}
	out := new(NodeStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *OperatorCondition) DeepCopyInto(out *OperatorCondition) {
	*out = *in
	in.LastTransitionTime.DeepCopyInto(&out.LastTransitionTime)
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new OperatorCondition.
func (in *OperatorCondition) DeepCopy() *OperatorCondition {
	if in == nil {
		return nil
	}
	out := new(OperatorCondition)
	in.DeepCopyInto(out)
	return out
}

func (in *OperatorSpec) DeepCopyInto(out *OperatorSpec) {
	*out = *in
	in.UnsupportedConfigOverrides.DeepCopyInto(&out.UnsupportedConfigOverrides)
	in.ObservedConfig.DeepCopyInto(&out.ObservedConfig)
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new OperatorSpec.
func (in *OperatorSpec) DeepCopy() *OperatorSpec {
	if in == nil {
		return nil
	}
	out := new(OperatorSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *OperatorStatus) DeepCopyInto(out *OperatorStatus) {
	*out = *in
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]OperatorCondition, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.Generations != nil {
		in, out := &in.Generations, &out.Generations
		*out = make([]GenerationStatus, len(*in))
		copy(*out, *in)
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new OperatorStatus.
func (in *OperatorStatus) DeepCopy() *OperatorStatus {
	if in == nil {
		return nil
	}
	out := new(OperatorStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *StaticPodOperatorSpec) DeepCopyInto(out *StaticPodOperatorSpec) {
	*out = *in
	in.OperatorSpec.DeepCopyInto(&out.OperatorSpec)
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new StaticPodOperatorSpec.
func (in *StaticPodOperatorSpec) DeepCopy() *StaticPodOperatorSpec {
	if in == nil {
		return nil
	}
	out := new(StaticPodOperatorSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *StaticPodOperatorStatus) DeepCopyInto(out *StaticPodOperatorStatus) {
	*out = *in
	in.OperatorStatus.DeepCopyInto(&out.OperatorStatus)
	if in.NodeStatuses != nil {
		in, out := &in.NodeStatuses, &out.NodeStatuses
		*out = make([]NodeStatus, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new StaticPodOperatorStatus.
func (in *StaticPodOperatorStatus) DeepCopy() *StaticPodOperatorStatus {
	if in == nil {
		return nil
	}
	out := new(StaticPodOperatorStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MachineConfiguration) DeepCopyInto(out *MachineConfiguration) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MachineConfiguration.
func (in *MachineConfiguration) DeepCopy() *MachineConfiguration {
	if in == nil {
		return nil
	}
	out := new(MachineConfiguration)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *MachineConfiguration) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MachineConfigurationList) DeepCopyInto(out *MachineConfigurationList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]MachineConfiguration, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MachineConfigurationList.
func (in *MachineConfigurationList) DeepCopy() *MachineConfigurationList {
	if in == nil {
		return nil
	}
	out := new(MachineConfigurationList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *MachineConfigurationList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MachineConfigurationSpec) DeepCopyInto(out *MachineConfigurationSpec) {
	*out = *in
	in.StaticPodOperatorSpec.DeepCopyInto(&out.StaticPodOperatorSpec)
	if in.InvisibleMetrics != nil {
		in, out := &in.InvisibleMetrics, &out.InvisibleMetrics
		*out = make([]InvisibleMetric, len(*in))
		copy(*out, *in)
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MachineConfigurationSpec.
func (in *MachineConfigurationSpec) DeepCopy() *MachineConfigurationSpec {
	if in == nil {
		return nil
	}
	out := new(MachineConfigurationSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *MachineConfigurationStatus) DeepCopyInto(out *MachineConfigurationStatus) {
	*out = *in
	in.StaticPodOperatorStatus.DeepCopyInto(&out.StaticPodOperatorStatus)
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new MachineConfigurationStatus.
func (in *MachineConfigurationStatus) DeepCopy() *MachineConfigurationStatus {
	if in == nil {
		return nil
	}
	out := new(MachineConfigurationStatus)
	in.DeepCopyInto(out)
	return out
}
