apiVersion: apiextensions.k8s.io/v1
Kind: CustomResourceDefinition
metadata:
  name: machinestate.machineconfiguration.openshift.io
  labels:
    "openshift.io/operator-managed": ""
  annotations:
    include.release.openshift.io/ibm-cloud-managed: "true"
    include.release.openshift.io/self-managed-high-availability: "true"
    include.release.openshift.io/single-node-developer: "true"
spec:
  # group name to use for REST API: /apis/<group>/<version>
  group: machineconfiguration.openshift.io
  scope: Cluster
  names:
    singular: machinestate
    kind: MachineState
    shortnames:
    - state
  versions:
  - name: v1
    # Each version can be enabled/disabled by Served flag.
    served: true
    # One and only one version must be marked as the storage version.
    storage: true
    subresources:
      status: {}
    additionalPrinterColumns:
    - jsonPath: config.kind
      name: Type
      type: string
    - jsonPath: status.healthy
      name: Healthy
      type: bool
    - jsonPath: status.progress[0].state
      name: Progress
      type: string
    - jsonPath: status.progress[0].node.name
      name: Machine
      type: string
    - jsonPath: status.error
      name: Error
      type: string
    schema:
      openAPIV3Schema:
        description: MachineState describes the health of the system.
        type: object
        properties:
          apiVersion:
            description: 'APIVersion defines the versioned schema of this representation
              of an object. Servers should convert recognized schemas to the latest
              internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources'
            type: string
          kind:
            description: 'Kind is a string value representing the REST resource this
              object represents. Servers may infer this from the endpoint the client
              submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds'
            type: string
          metadata:
            type: object
          spec:
            description: MachineStateConfig is the spec for the MachineState resource
            type: object
            properties:
              config:
                description: the targeted MachineState object for the machine state.
                type: object
                properties:
                  kind:
                    description: Kind is the type of state we are tracking.
                    type: string
          status:
            description: MachineStateStatus is the status of the MachineState resource.
            type: object
            properties:
              allStates:
                description: allStates tracks all possible states and their most recent progress.
                additionalProperties:
                  description: progessionCondition keeps track of the phase and reason of a specific state.
                  type: object
                  properties:
                    phase:
                      description: phase of our current state
                      type: string
                    reason:
                      description: reason describes why we are in the current state.
                      type: string
                properties:
                  state:
                    description: state is the progression state we are in
                    type: string
                  node:
                    description: node is the node on which the state of the MCO is occuring
                    type: object
                type: object
              progress:
                description: progress provides the user with the most recently reported state, or if not healthy the most recently errors state.
                type: string
              healthy:
                description: healthy reports to the user whether or not all states are reporting healthy.
                type: string
              error:
                description: error reports the last error state of the state controller.
                type: string



